//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System;
using System.Reflection;
using GodotSharpGDExtension;

[assembly:InternalsVisibleTo("ScriptInterop.CSharp")]

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace GDExtension
{
	using System.Runtime.InteropServices;

	public static unsafe class Native
	{
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
