name: 🤖 Android Builds
on: [push, pull_request]

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  build-linux-windows:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Android Build
            cache-name: android-template-release
            bin: "./platform/android/java/lib/build/outputs/aar/godot-lib.template_release.aar"
            artifact: true

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Linux dependencies for gold linker
        run: |
          sudo apt-get install -qq binutils

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup GCC problem matcher
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Compilation (arm32)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=arm32 library_type=shared_library
          platform: android
          target: template_release
          tests: false

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=arm64 library_type=shared_library
          platform: android
          target: template_release
          tests: false
        
      - name: Compilation (x86)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=x86 library_type=shared_library
          platform: android
          target: template_release
          tests: false
        
      - name: Compilation (x64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=x86_64 library_type=shared_library
          platform: android
          target: template_release
          tests: false

      - name: Generate Godot templates
        run: |
          cd godot/platform/android/java
          ./gradlew assemble
          cd ../../..
          ls -l bin/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: ${{ matrix.artifact }}
        with:
          name: ${{ matrix.cache-name }}
          path: ${{ matrix.bin }}