name: Build tools
on:
  push:
    branches:
      - '4.1_extension'


env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
    
jobs:
  build:
    runs-on: "windows-latest"
    environment: NugetBuildEnviroment
    name: 'NuGet Package Build'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: 'windows-64-editor'
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup MSVC problem matcher
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} library_type=shared_library
          platform: windows
          tests: false 
          
      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: windows-64-editor
          path: "godot/bin/*"         