/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_DotnetScriptInterop_WRAP_H_
#define SWIG_DotnetScriptInterop_WRAP_H_

class SwigDirector_FSharpScript : public FSharpScript, public Swig::Director {

public:
    SwigDirector_FSharpScript();
    virtual ~SwigDirector_FSharpScript();
    virtual std::vector< FSharpMethodInfo > _getMethods();

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)();
    void swig_connect_director(SWIG_Callback0_t callback_getMethods);

private:
    SWIG_Callback0_t swig_callback_getMethods;
    void swig_init_callbacks();
};


#endif
